# Generated by Django 5.2.4 on 2025-07-15 14:35

import authentication.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_avatar_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, default='profileImages/default.png', null=True, upload_to='profileImages/', validators=[authentication.validator.validate_image_type_and_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
