# Generated by Django 5.2.4 on 2025-08-09 03:23

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('laundry', 'Laundry'), ('attached_bathroom', 'Attached Bathroom'), ('meals', 'Meals Included'), ('housekeeping', 'Housekeeping'), ('parking', 'Parking'), ('cctv', 'CCTV'), ('study_table', 'Study Table'), ('wardrobe', 'Wardrobe'), ('water', '24x7 Water'), ('security', 'Security Guard'), ('power_backup', 'Power Backup'), ('fridge', 'Refrigerator'), ('tv', 'TV'), ('geyser', 'Geyser')], max_length=131, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
