# Generated by Django 5.2.4 on 2025-08-10 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_preferred_amenities_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_state',
            new_name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation_type',
            field=models.CharField(blank=True, choices=[('institution', 'Institution'), ('organization', 'Organization')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
