# Generated by Django 5.2.4 on 2025-08-10 05:54

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_location_city_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('pg', 'PG'), ('hostel', 'Hostel'), ('mess', 'Mess'), ('tiffin', 'Tiffin Service'), ('tutor', 'Tutor')], max_length=27),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
