# Generated by Django 5.2.4 on 2025-08-11 19:13

import django.core.validators
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Optional comment for the review.', validators=[django.core.validators.MinLengthValidator(4, message='Comment must be at least 4 characters.'), reviews.models.validate_not_only_digits]),
        ),
    ]
