# Generated by Django 5.2.4 on 2025-08-08 14:41

import listings.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/', validators=[listings.validator.validate_image_type_and_size]),
        ),
    ]
