# Generated by Django 5.2.4 on 2025-08-09 03:23

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='food_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('male', 'Male Only'), ('female', 'Female Only'), ('any', 'Any Gender')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='occupancy_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Room'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing'), ('quad', 'Four Sharing'), ('dorm', 'Dormitory')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('laundry', 'Laundry'), ('attached_bathroom', 'Attached Bathroom'), ('meals', 'Meals Included'), ('housekeeping', 'Housekeeping'), ('parking', 'Parking'), ('cctv', 'CCTV'), ('study_table', 'Study Table'), ('wardrobe', 'Wardrobe'), ('water', '24x7 Water'), ('security', 'Security Guard'), ('power_backup', 'Power Backup'), ('fridge', 'Refrigerator'), ('tv', 'TV'), ('geyser', 'Geyser')], max_length=255),
        ),
    ]
