# Generated by Django 5.2.4 on 2025-08-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_food_included_listing_gender_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='location_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
