# Generated by Django 5.2.4 on 2025-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_location_city_listing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
